### ISSUE TITLE
Friends requests & status

### ISSUE THREAD

**Issue by SaltyMilk** [pde-bakk/ft_transcendence#12]
![Screen Shot 2021-02-13 at 00 27 34](https://user-images.githubusercontent.com/59711209/107833078-70cbf680-6d92-11eb-9dde-ad1c408f954d.png)
Whenever I try to send add a friend it doesn't send a request. If both add each other however everything seems ok and they can see their relative status.
Another bug I found is status didn't work for some reason as you can see on attached screenshot.

**Comment by skrtks** [comment]
No that's true, I auto accept now, once we have multi users I want to turn that off so we can test it properly. Also for the status it has to be implemented with the multi users. Let's keep this open. I'll try to fix it once the auth system is finished.
