### ISSUE TITLE
Buttons don't always work on chat page

### ISSUE THREAD

**Issue by skrtks** [pde-bakk/ft_transcendence#23]
After switching away from and then back to the chat page, the "Message" buttons don't work anymore. This should be easy to fix by adding "this.views.[myview].delegateEvents();" to where you create your view. I looked in the chat router but I'm not sure were you put it.

**Comment by pde-bakk** [comment]
What does .delegateEvents(); do?

Also yeah, I realized today that I could've utilized routers better, I mostly discarded them and made my views do everything. I'll see if I can better that

**Comment by skrtks** [comment]
Check this in Slack: https://42born2code.slack.com/archives/G01KW4QMNTE/p1613733680015200
I had the same issue a few days ago so I wrote up a small explanation of what was going on. However, the way you implemented the router I'm not sure where you would put the .delegateEvents();

**Comment by pde-bakk** [comment]
Fixed in PR #19
