### ISSUE TITLE
Guild-invite names not being updated upon user rename

### ISSUE THREAD

**Issue by pde-bakk** [pde-bakk/ft_transcendence#28]
If you have a guild, there's a list of users you can invite to the guild.
If one of them changes their name, it won't reflect that ni the list until you refresh (so going to another page and coming back won't fix it)

**Comment by pde-bakk** [comment]
I noticed this in the "sam_wars" branch btw

**Comment by pde-bakk** [comment]
Actually , the same happens with the Guild opponents for a war.
If I have 2 sessions open (one in a private window), and user1 creates a new guild (or changes their name), user2 won't see the change until they press f5

**Comment by skrtks** [comment]
Ah yes the auto refreshing is disabled atm because it clutters the output from rails, you can enable it by uncommenting line 61-66 in "app/views/home/index.html.erb". It's not real time but every 15 sec
