### ISSUE TITLE
War invite not being sent

### ISSUE THREAD

**Issue by pde-bakk** [pde-bakk/ft_transcendence#29]
I noticed it seemed possible to send your own guild a war-invite,
and the "Sent" (should maybe be "Send") button doesnt trigger anything, it stays on the same form page for me

**Comment by skrtks** [comment]
It should be Send indeed :) 

You're right that your own guild is in the list, but you should get an error when actually sending the request

I don't have any problems with the send button. Are you sure all the fields are filled? It should give feedback when you forgot something but maybe you're not seeing that for some reason. Also the prize money cannot be more than the lowest balance of both guilds (if you created a new guild that's 0)

**Comment by pde-bakk** [comment]
I believe it was because i didnt read the form instructions thoroughly enough, it works
